Repository devinit/DIwebsite-redesign, pull requests merged in 2019-07, with the labels that each got.

#86 [Fix] filter by departments position
  di_website/common/base.py
  di_website/home/migrations/0003_auto_20190709_1248.py
  di_website/home/migrations/0004_auto_20190701_1601.py
  di_website/home/migrations/0005_auto_20190703_1650.py
  di_website/home/migrations/0006_auto_20190709_0857.py
  di_website/home/models.py
  di_website/ourteam/migrations/0001_initial.py
  di_website/ourteam/migrations/0002_auto_20190703_1650.py
  di_website/ourteam/migrations/0003_auto_20190709_0857.py
  di_website/settings/base.py
  di_website/templates/includes/heroes/hero.html
  di_website/templates/ourteam/our_team.html
  di_website/tests.py
  di_website/users/migrations/0001_initial.py
  di_website/users/migrations/0002_department_userprofile.py
  di_website/users/migrations/0003_auto_20190628_1724.py
  di_website/users/migrations/0004_auto_20190701_1601.py
  di_website/users/migrations/0005_department_slug.py
  di_website/users/migrations/0006_auto_20190703_1650.py
  di_website/users/models.py
Labels: CMS, Review Required, Technical Review

#88 Feature/vacancies
  di_website/common/base.py
  di_website/common/blocks.py
  di_website/common/constants.py
  di_website/common/migrations/0001_initial.py
  di_website/common/migrations/0002_download.py
  di_website/common/templatetags/string_utils.py
  di_website/context.py
  di_website/home/models.py
  di_website/home/templatetags/card_tags.py
  di_website/settings/base.py
  di_website/templates/404.html
  di_website/templates/500.html
  di_website/templates/blocks/banner_block.html
  di_website/templates/blocks/blockquote.html
  di_website/templates/blocks/embed_block.html
  di_website/templates/blocks/paragraph_block.html
  di_website/templates/home/home_page.html
  di_website/templates/includes/banner.html
  di_website/templates/includes/cards/card-job.html
  di_website/templates/includes/heroes/hero.html
  di_website/templates/layouts/default.html
  di_website/templates/layouts/sidebar.html
  di_website/templates/ourteam/our_team_page.html
  di_website/templates/ourteam/team_member_page.html
  di_website/templates/search/search.html
  di_website/templates/tags/cards/other_pages.html
  di_website/templates/vacancies/vacancy_index_page.html
  di_website/templates/vacancies/vacancy_page.html
  di_website/users/migrations/0004_subscription.py
  di_website/users/models.py
  di_website/vacancies/__init__.py
  di_website/vacancies/apps.py
  di_website/vacancies/migrations/0001_initial.py
  di_website/vacancies/migrations/0002_auto_20190717_1252.py
  di_website/vacancies/migrations/0003_auto_20190718_0624.py
  di_website/vacancies/migrations/__init__.py
  di_website/vacancies/models.py
  requirements.txt
Labels: CMS, Review Required, Technical Review

#103 Feature/blogs
  di_website/blog/__init__.py
  di_website/blog/apps.py
  di_website/blog/migrations/0001_initial.py
  di_website/blog/migrations/0002_auto_20190723_0458.py
  di_website/blog/migrations/__init__.py
  di_website/blog/models.py
  di_website/common/base.py
  di_website/common/blocks.py
  di_website/common/templatetags/string_utils.py
  di_website/settings/base.py
  di_website/templates/blocks/paragraph_block.html
  di_website/templates/blog/blog_article_page.html
  di_website/templates/blog/blog_index_page.html
  di_website/templates/includes/cards/card-blog.html
  di_website/templates/includes/heroes/hero-post.html
  di_website/templates/includes/heroes/hero.html
  di_website/templates/includes/partials/author-link.html
  di_website/templates/includes/partials/author.html
  di_website/templates/includes/scaffold/pagination-links.html
  di_website/templates/ourteam/our_team_page.html
  di_website/templates/vacancies/vacancy_page.html
  di_website/tests.py
  di_website/vacancies/migrations/0004_auto_20190719_1653.py
  di_website/vacancies/migrations/0005_auto_20190723_0458.py
Labels: Review Required, Technical Review

#107 Feature/news
  .editorconfig
  di_website/blog/models.py
  di_website/common/base.py
  di_website/common/constants.py
  di_website/news/__init__.py
  di_website/news/admin.py
  di_website/news/apps.py
  di_website/news/migrations/0001_initial.py
  di_website/news/migrations/0002_newsindexpage_intro.py
  di_website/news/migrations/__init__.py
  di_website/news/models.py
  di_website/settings/base.py
  di_website/templates/includes/cards/card-news.html
  di_website/templates/includes/cards/card-related.html
  di_website/templates/includes/heroes/hero-news.html
  di_website/templates/news/news_index_page.html
  di_website/templates/news/news_story_page.html
  di_website/vacancies/migrations/0006_auto_20190729_1254.py
  di_website/vacancies/models.py
Labels: CMS, Technical Review

#113 Fix/related-links
  di_website/blog/migrations/0003_auto_20190731_1608.py
  di_website/blog/models.py
  di_website/common/base.py
  di_website/common/migrations/0003_delete_otherpage.py
  di_website/news/migrations/0003_auto_20190731_1430.py
  di_website/news/migrations/0004_auto_20190731_1608.py
  di_website/news/models.py
  di_website/vacancies/migrations/0007_vacancyrelatedlink.py
  di_website/vacancies/migrations/0008_auto_20190731_1608.py
  di_website/vacancies/models.py
Labels: CMS, Technical Review
