Repository devinit/DIwebsite-redesign, pull requests merged in 2019-08, with the labels that each got.

#115 Fix/related links
  di_website/news/models.py
  di_website/templates/blog/blog_article_page.html
  di_website/templates/includes/partials/author.html
  di_website/templates/news/news_story_page.html
Labels: CMS, Technical Review, bug

#122 Feature/breadcrumbs
  di_website/home/templatetags/navigation_tags.py
  di_website/templates/tags/navigation/breadcrumbs.html
  di_website/templates/vacancies/vacancy_index_page.html
  di_website/templates/vacancies/vacancy_page.html
Labels: CMS, Technical Review

#133 Feature/standard page
  di_website/blog/migrations/0004_auto_20190802_0914.py
  di_website/blog/migrations/0005_auto_20190802_1433.py
  di_website/blog/models.py
  di_website/common/base.py
  di_website/common/blocks.py
  di_website/common/edit_handlers.py
  di_website/common/mixins.py
  di_website/home/migrations/0005_standardpage_standarpagerelatedlink.py
  di_website/home/migrations/0006_auto_20190802_1433.py
  di_website/home/models.py
  di_website/news/migrations/0005_auto_20190802_1433.py
  di_website/news/models.py
  di_website/ourteam/migrations/0004_auto_20190802_0914.py
  di_website/ourteam/models.py
  di_website/templates/blocks/banner/banner_block.html
  di_website/templates/blocks/banner/list.html
  di_website/templates/blocks/banner/list_item.html
  di_website/templates/blocks/banner/text.html
  di_website/templates/blocks/banner_block.html
  di_website/templates/blocks/section_blockquote.html
  di_website/templates/blocks/section_paragraph_block.html
  di_website/templates/blog/blog_article_page.html
  di_website/templates/home/standard_page.html
  di_website/templates/includes/banner.html
  di_website/templates/tags/navigation/secondary.html
  di_website/vacancies/migrations/0009_auto_20190802_1433.py
  di_website/vacancies/models.py
Labels: CMS, Technical Review

#141 [Fix] strip tags from card-news.html
  di_website/templates/includes/cards/card-blog.html
  di_website/templates/includes/cards/card-news.html
Labels: CMS

#151 No row narrow for news story since it inherits from sidebar
  di_website/templates/news/news_story_page.html
Labels: bug

#153 Multi-departments
  di_website/common/management/commands/importwp.py
  di_website/ourteam/migrations/0005_auto_20190807_1400.py
  di_website/ourteam/models.py
  di_website/tests.py
Labels: bug

#154 Profile image idempotence
  di_website/common/management/commands/importwp.py
Labels: bug

#155 Order departments
  di_website/users/migrations/0005_auto_20190808_1403.py
  di_website/users/models.py
Labels: enhancement

#159 [Update] default card images
  di_website/templates/includes/cards/card-blog.html
  di_website/templates/includes/cards/card-event.html
  di_website/templates/includes/cards/card-news.html
  di_website/templates/includes/cards/card-related.html
Labels: bug

#158 Pretty pagination
  di_website/common/base.py
  di_website/templates/includes/scaffold/pagination.html
Labels: bug

#160 Format j F Y for e.g. 10 October 2019
  di_website/templates/includes/cards/card-blog.html
  di_website/templates/includes/cards/card-member-content.html
  di_website/templates/includes/cards/card-news.html
  di_website/templates/includes/cards/card-related.html
  di_website/templates/includes/heroes/hero-news.html
  di_website/templates/includes/heroes/hero-post.html
Labels: bug

#157 Feature/places
  .editorconfig
  di_website/blog/migrations/0007_auto_20190809_1012.py
  di_website/common/blocks.py
  di_website/common/constants.py
  di_website/events/migrations/0008_auto_20190809_1012.py
  di_website/home/migrations/0008_auto_20190809_1012.py
  di_website/home/migrations/0009_auto_20190812_0804.py
  di_website/home/migrations/0010_standardpage_other_pages_heading.py
  di_website/home/migrations/0011_auto_20190812_0817.py
  di_website/home/models.py
  di_website/news/migrations/0007_auto_20190809_1012.py
  di_website/place/__init__.py
  di_website/place/admin.py
  di_website/place/apps.py
  di_website/place/blocks.py
  di_website/place/migrations/0001_initial.py
  di_website/place/migrations/0002_auto_20190809_1202.py
  di_website/place/migrations/0003_placespage_other_pages_heading.py
  di_website/place/migrations/__init__.py
  di_website/place/models.py
  di_website/settings/base.py
  di_website/templates/blocks/place_block.html
  di_website/templates/home/standard_page.html
  di_website/templates/includes/cards/card-related.html
  di_website/templates/includes/partials/project.html
  di_website/templates/place/places_page.html
  di_website/templates/vacancies/vacancy_page.html
  di_website/vacancies/migrations/0011_auto_20190809_1012.py
  di_website/vacancies/migrations/0012_auto_20190812_0804.py
  di_website/vacancies/models.py
Labels: CMS

#161 [Update] hero_class block on hero template
  di_website/templates/includes/heroes/hero-news.html
  di_website/templates/includes/heroes/hero-post.html
  di_website/templates/includes/heroes/hero.html
Labels: CMS, bug

#173 Feature/contactus
  di_website/common/templatetags/form_utils.py
  di_website/contactus/__init__.py
  di_website/contactus/apps.py
  di_website/contactus/migrations/0001_initial.py
  di_website/contactus/migrations/__init__.py
  di_website/contactus/models.py
  di_website/contactus/utils.py
  di_website/settings/base.py
  di_website/templates/contactus/contact_page.html
  di_website/templates/contactus/contact_page_landing.html
  di_website/templates/contactus/includes/contact_details.html
  di_website/templates/contactus/includes/form-loop.html
  requirements.txt
Labels: Review Required

#162 Start of our story template page
  di_website/about/__init__.py
  di_website/about/apps.py
  di_website/about/migrations/0001_initial.py
  di_website/about/migrations/0002_auto_20190819_0751.py
  di_website/about/migrations/0003_auto_20190819_0838.py
  di_website/about/migrations/0004_remove_whowearepage_locations.py
  di_website/about/migrations/0005_auto_20190819_1009.py
  di_website/about/migrations/0006_auto_20190819_1013.py
  di_website/about/migrations/0007_auto_20190819_1017.py
  di_website/about/migrations/__init__.py
  di_website/about/models.py
  di_website/blog/migrations/0008_auto_20190813_1221.py
  di_website/blog/migrations/0009_auto_20190814_1527.py
  di_website/blog/migrations/0010_auto_20190819_0751.py
  di_website/blog/migrations/0011_auto_20190819_1017.py
  di_website/common/blocks.py
  di_website/common/mixins.py
  di_website/events/migrations/0009_auto_20190813_1221.py
  di_website/events/migrations/0010_auto_20190814_1527.py
  di_website/events/migrations/0011_auto_20190819_0751.py
  di_website/events/migrations/0012_auto_20190819_1017.py
  di_website/home/migrations/0012_auto_20190813_1221.py
  di_website/home/migrations/0013_auto_20190814_1527.py
  di_website/home/migrations/0014_auto_20190819_0751.py
  di_website/home/migrations/0015_auto_20190819_1017.py
  di_website/home/templatetags/card_tags.py
  di_website/news/migrations/0008_auto_20190813_1221.py
  di_website/news/migrations/0009_auto_20190814_1527.py
  di_website/news/migrations/0010_auto_20190819_0751.py
  di_website/news/migrations/0011_auto_20190819_1017.py
  di_website/place/migrations/0004_auto_20190813_1221.py
  di_website/place/migrations/0005_auto_20190814_1527.py
  di_website/place/migrations/0006_auto_20190819_0751.py
  di_website/place/migrations/0007_auto_20190819_1017.py
  di_website/settings/base.py
  di_website/templates/about/our_story_page.html
  di_website/templates/about/who_we_are_page.html
  di_website/templates/blocks/banner/banner_block.html
  di_website/templates/blocks/banner/button_block.html
  di_website/templates/blocks/button_block.html
  di_website/templates/blocks/documentbox_block.html
  di_website/templates/blocks/documentboxsection_block.html
  di_website/templates/blocks/link_block.html
  di_website/templates/blocks/timeline_carousel.html
  di_website/templates/blocks/value_block.html
  di_website/vacancies/migrations/0013_auto_20190813_1221.py
  di_website/vacancies/migrations/0014_auto_20190814_1527.py
  di_website/vacancies/migrations/0015_auto_20190819_0751.py
  di_website/vacancies/migrations/0016_auto_20190819_0927.py
  di_website/vacancies/migrations/0017_auto_20190819_0929.py
  di_website/vacancies/migrations/0018_auto_20190819_1017.py
  di_website/vacancies/models.py
Labels: enhancement

#174 Feature/01d media center
  di_website/news/migrations/0008_auto_20190815_1850.py
  di_website/news/migrations/0009_auto_20190815_1902.py
  di_website/news/models.py
  di_website/templates/blocks/person_block.html
  di_website/templates/news/media_center_page.html
Labels: enhancement

#176 Merge news migrations
  di_website/news/migrations/0012_merge_20190819_1451.py
  di_website/news/migrations/0013_auto_20190819_1451.py
Labels: bug

#177 Several unrelated fixes
  di_website/about/migrations/0008_auto_20190820_0900.py
  di_website/about/models.py
  di_website/common/blocks.py
  di_website/home/migrations/0016_auto_20190820_0825.py
  di_website/home/migrations/0017_auto_20190820_0900.py
  di_website/home/models.py
  di_website/templates/about/our_story_page.html
  di_website/templates/about/who_we_are_page.html
  di_website/templates/blocks/image_block.html
  di_website/templates/home/standard_page.html
  di_website/templates/place/places_page.html
Labels: CMS, bug

#182 Fix/contact us
  di_website/contactus/migrations/0002_auto_20190819_0934.py
  di_website/contactus/models.py
  di_website/contactus/utils.py
  di_website/templates/contactus/contact_page_landing.html
  di_website/templates/contactus/includes/contact_details.html
Labels: Review Required

#143 Feature/project
  .editorconfig
  di_website/project/__init__.py
  di_website/project/admin.py
  di_website/project/apps.py
  di_website/project/migrations/0001_initial.py
  di_website/project/migrations/0002_projectpagerelatedlink.py
  di_website/project/migrations/0003_projectpagerelatedlink_title.py
  di_website/project/migrations/0004_auto_20190806_1342.py
  di_website/project/migrations/0005_auto_20190806_1508.py
  di_website/project/migrations/0006_auto_20190808_1144.py
  di_website/project/migrations/0007_auto_20190814_0515.py
  di_website/project/migrations/0008_projectpagerelatedlink_extra_page.py
  di_website/project/migrations/0009_auto_20190814_0631.py
  di_website/project/migrations/0010_auto_20190814_1136.py
  di_website/project/migrations/0011_focusareaspagerelatedlink.py
  di_website/project/migrations/0012_auto_20190816_1042.py
  di_website/project/migrations/0013_auto_20190820_1209.py
  di_website/project/migrations/0014_auto_20190820_1220.py
  di_website/project/migrations/0015_auto_20190820_1242.py
  di_website/project/migrations/0016_auto_20190820_1401.py
  di_website/project/migrations/0017_auto_20190820_1402.py
  di_website/project/migrations/0018_auto_20190820_1420.py
  di_website/project/migrations/0019_auto_20190820_1523.py
  di_website/project/migrations/0020_auto_20190821_0145.py
  di_website/project/migrations/0021_auto_20190823_1256.py
  di_website/project/migrations/0022_auto_20190823_1431.py
  di_website/project/migrations/__init__.py
  di_website/project/models.py
  di_website/settings/base.py
  di_website/templates/includes/cards/card-more-about.html
  di_website/templates/includes/partials/focus_areas.html
  di_website/templates/project/focus_areas_page.html
  di_website/templates/project/project_page.html
Labels: Technical Review
