Repository devinit/DIwebsite-redesign, pull requests merged in 2019-09, with the labels that each got.

#200 Add multiple authors to blog and fix blog management command
  di_website/blog/migrations/0014_auto_20190905_1556.py
  di_website/blog/migrations/0015_auto_20190905_1713.py
  di_website/blog/models.py
  di_website/common/management/commands/fixblogs.py
  di_website/common/management/commands/importwp.py
  di_website/templates/blog/blog_article_page.html
  di_website/templates/includes/cards/card-blog.html
  di_website/templates/includes/heroes/hero-post.html
  di_website/templates/includes/partials/multi-authors.html
Labels: enhancement

#210 Replace button class
  di_website/common/management/commands/importwp.py
Labels: bug

#225 Feature/page notifications
  di_website/blog/models.py
  di_website/common/base.py
  di_website/common/management/commands/send_page_notifications.py
  di_website/common/migrations/0005_pagenotification.py
  di_website/common/migrations/0006_auto_20190924_0826.py
  di_website/common/wagtail_hooks.py
  di_website/contactus/models.py
  di_website/events/models.py
  di_website/general/models.py
  di_website/home/models.py
  di_website/news/models.py
  di_website/ourteam/models.py
  di_website/place/models.py
  di_website/project/models.py
  di_website/publications/models.py
  di_website/static/css/admin.css
  di_website/templates/wagtailadmin/base.html
  di_website/templates/wagtailadmin/login.html
  di_website/vacancies/models.py
  di_website/whatwedo/models.py
  di_website/workforus/models.py
Labels: CMS, Review Required
